---
backup:
  # Schedule
  schedule: "0 0 * * *"
  # Name of the backup (if not defined, defaults to the database name)
  name: ""
# Connection to the PG cluster
connection:
  # Host name or IP
  host: ""
  # Port to reach the PG cluster
  port: 0
# Credentials to connect to the PG cluster as DB admin
auth:
  # User name
  username: ""
  # Password
  password: ""
# Database to backup
database:
  # Version of PG to use
  version: 15
  # Name of the database to backup
  name: ""
# Digital Ocean setup
digitalocean:
  # Space to target
  space:
    # Access key
    accessKey: ""
    # Secret key
    secretKey: ""
    # Name of the secret containing the keys
    secretName: ""
    # Region
    region: "fra1"
    # Bucket
    bucket: "ontrack-run-do-env-production-eu-cluster-database-backup"
    # Path definition
    path:
      # Root
      root: sql
