---
backup:
  # Schedule
  schedule: "0 0 * * *"
  # Name of the backup (if not defined, defaults to the database name)
  name: ""
# Connection to the PG cluster
connection:
  # Host name or IP
  host: ""
  # Port to reach the PG cluster
  port: 0
  # SSL mode
  ssl: require
# Credentials to connect to the PG cluster as DB admin
auth:
  # User name
  username: ""
  # Password
  password: ""
# Database to backup
database:
  # Version of PG to use
  version: 15
  # Name of the database to backup
  name: ""
# Digital Ocean setup
digitalocean:
  # Space to target
  space:
    # Access key
    accessKey: ""
    # Secret key
    secretKey: ""
    # Name of the secret containing the keys
    secretName: ""
    # Using an external secret
    externalSecret:
      # Enabling the creation of an external secret
      enabled: false
      # Refresh interval
      refreshInterval: 6h
      # Secret store
      store:
        # Name of the secrets store
        name: vault-backend
        # Kind of the secrets store
        kind: ClusterSecretStore
        # Path to the secret in the KV engine
        path: digitalocean/space
        # Name of the access key
        accessKeyName: accessKey
        # Name of the secret key
        secretKeyName: secretKey
      # Secret to create
      secret:
        # Name of the secret to create
        name: db-backup
    # Region
    region: "fra1"
    # Bucket
    bucket: "ontrack-run-do-env-production-eu-cluster-database-backup"
    # Path definition
    path:
      # Root
      root: sql
