{{- if .Values.digitalocean.space.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ or .Values.backup.name .Values.database.name }}-external-secret
spec:
  refreshInterval: {{ .Values.digitalocean.space.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.digitalocean.space.externalSecret.store.name | quote }}
    kind: {{ .Values.digitalocean.space.externalSecret.store.kind }}
  target:
    name: {{ .Values.digitalocean.space.externalSecret.secret.name | quote }}
  data:
    - secretKey: accessKey
      remoteRef:
        key: {{ .Values.digitalocean.space.externalSecret.store.path | quote }}
        property: {{ .Values.digitalocean.space.externalSecret.store.accessKeyName | quote }}
    - secretKey: secretKey
      remoteRef:
        key: {{ .Values.digitalocean.space.externalSecret.store.path | quote }}
        property: {{ .Values.digitalocean.space.externalSecret.store.secretKeyName | quote }}
{{- end }}
